apiVersion: v1
kind: ConfigMap
metadata:
  name: server-management-service-env
  namespace: dune-system
data:
  DUNE_SERVICE_TIME_ZONE: "America/Vancouver"
  DUNE_RESTART_TIME_ZONE: "America/Vancouver"
  DUNE_STEAMCMD: "/home/dune/.local/share/Steam/steamcmd/steamcmd.sh"
